# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "碎碎念"
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  自律是解决人生问题最主要的工具，也是消除人生痛苦最重要的方法
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wywon.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

kramdown:
 input: GFM
 syntax_highlighter: rouge

highlighter: rouge
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

# post date timezone
future: true

# Outputting
permalink: /:categories/:year/:month/:day/:title.html
paginate: 10
paginate_path: "/page:num/"
timezone: null

collections:
 photos:
  output: true
  permalink: /:collection/:year/:month/:day/:title.html
 quotes:
  output: true
  permalink: /:collection/:year/:month/:day/:title.html
 menu:
  output: true
  permalink: /:collection/:year/:month/:day/:title.html

theme: jekyll-theme-tactile

# Staticman comments
staticmanUrl: https://api.staticman.net/v3/entry/github/huwewa/huwewa.github.com/master/comments
