# Site settings
title: "碎碎念"
# email: huwewa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  思绪稍纵即逝，偶尔在这里停留。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wywon.com" # the base hostname & protocol for your site
# twitter_username: huwewa
# github_username:  huwewa

# Build settings
markdown: kramdown
#markdown: redcarpet #enable the code block ```
kramdown:
   input: GFM
   hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate

# post date timezone
future: true

# Outputting
permalink: /:year/:month/:day/:title.html
paginate: 10
paginate_path: "page:num"
timezone: null
